name: csp-front

services:
  csp-front:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: csp-front
    ports:
      - "4200:80"
    networks:
      - csp-frontend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    restart: unless-stopped

networks:
  csp-frontend:
    external: true
    name: csp-frontend
